# Generated by Django 5.0.3 on 2024-04-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_pic",
            field=models.FileField(null=True, upload_to="user_pic/"),
        ),
    ]
